### ISSUE TITLE
MacOS Chrome bug

### ISSUE THREAD

**Issue by kloudmm** [UTAS-HealthSciences/mylo-mate#27] opened 2018-02-21 05:29 UTC
Scott McIntyre reports that his nav bar icons (including unit outline) have all disappeared. He says he upgraded to the latest version recently, not sure if that's coincidental. He shared his screen with me and I confirmed the options look fine and the options themselves are working, dev2 was able to be flicked on and off. Biggest clue is that the navbar icons _were working in dev2_, but not in normal MyLO. Console showed no errors in either case.

**Comment by connordeckers** [comment] 2018-02-22 04:33
I cannot reproduce this at all. I've loaded up the exact same unit in Chrome on my own macbook, and it works fine.

I have called Scott and run through:
- Checking the stored settings to make sure they had the right variable name (just in case)
- Creating a fresh new Chrome user and testing it through there
Both failed to display the unit admin icons.

I've tested on my Mac using both defaults and dev defaults, and neither had the desired effect.

I think we'll need to sit and discuss what could possibly be causing this, and go from there.

**Comment by connordeckers** [comment] 2018-02-23 03:41
Scotts issue seems to have cleared itself up. Unsure what might have changed, if anything. Possibly a chrome update in the background?

**Comment by connordeckers** [comment] 2018-02-23 04:55
This is on hold, in case someone else reports the issue.

**Comment by connordeckers** [comment] 2018-03-08 00:40
Temporarily closing to remove from the issues list. Will continue to remain in "Stalled / Paused / Waiting" column.

**Closed by connordeckers** 2018-03-08 00:40 UTC
Labels: bug, low priority, on hold
